GOOGLE_API_KEY = "AIzaSyDxuM1K2z4NTcMxAqXBrBLECRg0pSEFfw8"
#snowflake credentials not to show 

[snowflake]
user = "SravikaPadakanti"
password = "jFbvvBjLMV5JKn8"
account = "hxkwyoy-sl90061"
warehouse = "CULTURAL_WH"
database = "CULTURAL_HERITAGE_DB"
schema = "CULTURAL_SCHEMA"
